Add Maintenance Alert
CodeForAfrica/ckanext-openafrica pull request #43
Opened 2018-02-26 13:31 UTC by phillipahereza

## Description

Add maintenance alert strip on openAFRICA above the nav bar

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
![screencapture-192-168-33-60-5000-1519651312393](https://user-images.githubusercontent.com/13383422/36672917-22dee4da-1b12-11e8-90cb-fdd561b5708d.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2018-02-26 14:57 UTC, DavidLemayian requested changes

2018-02-26 14:57 UTC, DavidLemayian commented on ckanext/openafrica/templates/header.html
> +        <div class="alert alert-info alert-dismissible text-center" role="alert">
Please check indentation. It looks off.

2018-02-26 14:58 UTC, DavidLemayian commented
I'd like the alert to look as such with the dismiss button at the far right of course:

![36672917-22dee4da-1b12-11e8-90cb-fdd561b5708d](https://user-images.githubusercontent.com/877919/36677163-90748264-1b1e-11e8-88c5-4def30c57c49.png)

2018-02-26 14:59 UTC, DavidLemayian commented
Is there a "notification" system in CKAN that perhaps takes advantage of sessions to avoid showing the alert if it's already been dismissed once?

2018-02-27 09:14 UTC, phillipahereza commented
There's no notification system, but I could use the browser sessionStorage using js

2018-03-07 13:54 UTC, DavidLemayian commented
@phillipahereza There are conflicts and what's with the text shadow?

2018-03-09 13:48 UTC, DavidLemayian commented
@phillipahereza The dates here need to change..

2018-03-11 11:23 UTC, DavidLemayian commented
@phillipahereza Let's update the screenshot so we can see what it looks like.

You'll also notice that the language specifies GMT and not EAT in the screenshot I shared. And the specific timeline. Let's change this.

2018-03-11 13:01 UTC, merged